const { Router } = require('express');
const router = Router();
const userCtrl = require('../controllers/user');
const adminCtrl = require('../controllers/admin');

router.post('/login', userCtrl.login);
router.get('/verifyToken', userCtrl.checkToken, userCtrl.verifyToken)
router.get('/games', userCtrl.checkToken, userCtrl.getPlayingGames);
router.get('/game/:gameid', userCtrl.checkToken, userCtrl.getGame);
router.get('/games/position', userCtrl.checkToken, userCtrl.getPosInGames);
router.get('/game/:gameid/shares', userCtrl.checkToken, userCtrl.getSharesInGame);
router.get('/share/:gameid/share/:sharecode/historical', userCtrl.checkToken, userCtrl.getHistoricalShare);
router.get('/game/:gameid/shares/stock', userCtrl.checkToken, userCtrl.getSharesStock);
router.get('/game/:gameid/transactions', userCtrl.checkToken, userCtrl.getTransactions);
router.post('/game/:gameid/transactions', userCtrl.checkToken, userCtrl.createTransaction);
router.get('/game/:gameid/currencytransactions', userCtrl.checkToken, userCtrl.getCurrencyTransactions);
router.post('/game/:gameid/currencytransactions', userCtrl.checkToken, userCtrl.createCurrencyTransaction);
router.get('/profile', userCtrl.checkToken, userCtrl.getProfile);
router.put('/profile', userCtrl.checkToken, userCtrl.updateProfile);
router.get('/recoverpassword/:username', userCtrl.recoverPassword);
router.get('/user/:userid', userCtrl.checkToken, userCtrl.getUser);
router.get('/teams/owner', userCtrl.checkToken, userCtrl.getOwnerTeams);
router.get('/teams', userCtrl.checkToken, userCtrl.getPlayingTeams);
router.post('/teams', userCtrl.checkToken, userCtrl.createTeam);
router.post('/team/:teamid/login', userCtrl.checkToken, userCtrl.switchToTeam);
router.get('/teams/invitations', userCtrl.checkToken, userCtrl.getTeamInvitations);
router.post('/teams/invite/:username', userCtrl.checkToken, userCtrl.inviteToTeam);
router.post('/team/:teamid/acceptinvite', userCtrl.checkToken, userCtrl.acceptTeamInvitation);

router.post('/admin/users', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.createUser);
router.delete('/admin/user/:userid', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.deleteUser);
router.delete('/admin/user/:userid/makeadmin', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.toggleAdmin);
router.get('/admin/users', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getUsers);
router.get('/admin/user/:userid', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getUser);
router.get('/admin/teams', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getTeams);
router.get('/admin/team/:teamid', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getTeam);
router.get('/admin/user/:userid/wins', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getUserWins);
router.get('/admin/game/:gameid/winners', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getUsers);
router.post('/admin/games', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.createGame);
router.get('/admin/users', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getUsers);
router.delete('/admin/game/:gameid', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.deleteGame);
router.post('/admin/game/:gameid/end', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.endGame);
router.get('/admin/game/:gameid', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getGame);
router.get('/admin/games', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getGames);
router.get('/admin/game/:gameid/transactions', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getGameTransactions);
router.get('/admin/game/:gameid/currencytransactions', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getGameCurrencyTransactions);
router.get('/admin/users', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getUsers);
router.get('/admin/shares', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getShares);
router.post('/admin/shares', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.createShare);
router.get('/admin/share/:sharecode', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getShare);
router.get('/admin/game/:gameid/shares', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getGameShares);
router.get('/admin/currencies', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getCurrencies);
router.post('/admin/currencies', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.createCurrency);
router.get('/admin/currency/:currencycode', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getCurrency);
router.get('/admin/game/:gameid/currencies', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getGameCurrencies);
router.get('/admin/commodities', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getCommodities);
router.post('/admin/commodities', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.createCommodity);
router.get('/admin/commodity/:commoditycode', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getCommodity);
router.get('/admin/game/:gameid/commodities', userCtrl.checkToken, adminCtrl.checkAdmin, adminCtrl.getGameCommodities);

module.exports = router;